### ISSUE TITLE
Stuck after "Total Number of PDF Files Found: 1"

### ISSUE THREAD

**Issue by ronin08** [ViKi-R/pdf-watermark-remover#1]

**Comment by 0xViKi** [comment]
Hello @ronin08 If pdf has a lot of pages it takes time to process it.

Alternatively,

1. try updating the libraries
2. if it has error uncomment Line 20 and 40 for debugging and attach screenshot.

Thanks for finding issue 👍

**Comment by ronin08** [comment]
> Hello @ronin08 If pdf has a lot of pages it takes time to process it.
> 
> Alternatively,
> 
> 1. try updating the libraries
> 2. if it has error uncomment Line 20 and 40 for debugging and attach screenshot.
> 
> Thanks for finding issue 👍

Can you please try to remove watermark from this file. 
I have removed all other types of watermarks except the center one.

File link
 https://drive.google.com/uc?id=11ywX9v4H656STkbZl79YjF_SqnXNF1BO

**Comment by 0xViKi** [comment]
> 
> Can you please try to remove watermark from this file. I have removed all other types of watermarks except the centre one.
> 
> File link https://drive.google.com/uc?id=11ywX9v4H656STkbZl79YjF_SqnXNF1BO

So the file is password protected, it does not work with these kind of files.

**Comment by ronin08** [comment]
got it
